config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {:registrations => "registrations"}
  
  resources :patients do
    resource :team do
      resources :appointments do
        get :autocomplete_user_email, on: :collection
      end
      resources :team_memberships
      resources :invites
    end
  end
  

  
  
  

  get 'about' => 'welcome#about'
  
  root to: 'welcome#index'

end

app/models/patient.rb
class Patient < ActiveRecord::Base
    has_one :team
    has_many :team_memberships, through: :team
    has_many :users, through: :team_memberships
    belongs_to :account, class_name: "User", foreign_key: "user_id"
    validates :name, :length => {
    :minimum   => 1,
    :maximum   => 128
     }
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  def index
    @patients = policy_scope(Patient)
  end

  def show
    @patient = Patient.find(params[:id])
    # authorize @patient
  end

  def new
    @patient = Patient.new
    # authorize @patient
  end
  
  def create
    @patient = Patient.new(patient_params)
    @patient.creator_id = current_user.id
    patient_creation = PatientCreationService.new(@patient)
    # authorize @patient
    if patient_creation.perform
      flash[:notice] = "#{@patient.name} was saved as a patient."
      redirect_to [@patient]
    else
      flash[:notice] = "There was an error saving the patient. Please try again."
      render :new
    end
  end

  def edit
    @patient = Patient.find(params[:id])
    # authorize @patient
  end
  
  def update
    @patient = Patient.find(params[:id])
    # authorize @patient
    if @patient.update(patient_params)
      flash[:notice] = "#{@patient.name}'s information was updated."
      redirect_to [@patient]
    else
      flash[:notice] = "There was an error updating #{@patient.name}'s information. Please try again."
      render :edit
    end
  end
  
  private
  
  def patient_params
     params.require(:patient).permit(:name, :age, :address)
  end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_form.html.erb
<%= form_for @patient do |f| %>

    <div class='form-group'>
        <%= f.label :name %></br>
        <%= f.text_field :name %>
    </div>
     <div class='form-group'>
        <%= f.label :age %></br>
        <%= f.text_field :age %>
    </div>
    <div class='form-group'>
        <%= f.label :address %></br>
        <%= f.text_area :address %>
    </div>

    <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
    </div>
<% end %>

app/views/patients/edit.html.erb
<h1>Edit #{@patient.name}</h1>
<%= render "form" %>

app/views/patients/index.html.erb
<h3> My Patient Teams </h3>
<% if @patients %>
    <% @patients.each do |patient| %>
        <li><%= link_to patient.name, patient %></li>
    <% end %>
<% end %>

app/views/patients/new.html.erb
<h1>Create a Patient</h1>
<%= render "form" %>

app/views/patients/show.html.erb
<h1><%= @patient.name %></h1>
<ul>
    <li>Age: <%= @patient.age %></li>
    <li>Address: <%= @patient.address %></li>
</ul>

<%= link_to "Team", patient_team_path(@patient) %>