config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {:registrations => "registrations"}
  
  resources :patients do
    resource :team do
      resources :appointments do
        get :autocomplete_user_email, on: :collection
      end
      resources :team_memberships
      resources :invites
    end
  end
  

  
  
  

  get 'about' => 'welcome#about'
  
  root to: 'welcome#index'

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
    belongs_to :team
    validates :datetime, :presence => true
    belongs_to :assigned_user, :class_name => 'User'
    belongs_to :suggested_user, :class_name => 'User'
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
    autocomplete :user, :email
    # def index
    #     @team = Team.find(params[:id])
    #     @appointments = @team.appointments
    # end
    
    def show
        @patient = Patient.find(params[:patient_id])
        @team = @patient.team
        @appointment = Appointment.find(params[:id])
    end
    
    def new
        @patient = Patient.find(params[:patient_id])
        @team = @patient.team
        @appointment = Appointment.new
    end
    
    def create
        @appointment = Appointment.new(appointment_params)
        @patient = Patient.find(params[:patient_id])
        @team = @patient.team
        @appointment.team = @team
        @appointment.creating_user_id = current_user.id
        # @appointment.suggested_user_id = User.find_by_email(params[:user_email])
        @appointment.assigned_user_id = current_user.id if @appointment.assigned_user == 1
        if @appointment.save
            flash[:notice] = "#{@appointment.team.patient}'s appointment with #{@appointment.doctor} was saved succesfully."
            redirect_to [@patient, @team]
        else
            flash[:error] = "There was an error saving the appointment. Please try again."
            render :new
        end
    end
    
    def edit
        @patient = Patient.find(params[:patient_id])
        @appointment = Appointment.find(params[:id])
    end
    
    def update
        @patient = Patient.find(params[:patient_id])
        @appointment = Appointment.find(params[:id])
        if @appointment.update_attributes(appointment_params)
            flash[:notice] = "#{@appointment.team.patient.name}'s appointment has been successfully updated."
            redirect_to patient_team_path
        else
            flash[:notice] = "There was an error updating #{@appointment.team.patient.name}'s appointment. Please try again."
            render :edit
        end
    end
    
    def destroy
        @patient = Patient.find(params[:patient_id])
        @appointment = Appointment.find(params[:id])
        @appointment.assigned_user = current_user if @appointment.assigned_user == 1
        if @appointment.destroy
            flash[:notice] = "#{@appointment.team.patient}'s appointment was deleted."
            redirect_to patient_team_path
        else
            flash[:error] = "Error deleting appointment. Please try again."
            render :show
        end
    end

    private
    
    def appointment_params
        params.require(:appointment).permit(:title, :doctor, :address, :datetime, :suggested_user_id)
    end
end

app/helpers/appointment_helper.rb
module AppointmentHelper
end

app/views/appointments/_form.html.erb
<%= form_for [@patient, :team, @appointment] do |f| %>

    <div class='form-group'>
        <%= f.label :title %></br>
        <%= f.text_field :title %>
    </div>
    <div class='form-group'>
        <%= f.label :doctor %></br>
        <%= f.text_field :doctor %>
    </div>
      <div class='form-group'>
        <%= f.datetime_select :datetime, ampm: :true %>
    </div>
    
    <div class="form-group">
        <%= f.label :suggested_team_member %>
        <%= collection_select :appointment, :suggested_user_id, @patient.users, :id, :email, :include_blank => true %>
    </div>
    
    <div class="form-group">
        <%= f.label :assign_appointment_to_myself %>
        <%= check_box_tag :assign_appointment_to_myself %>
    </div>
    
     <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
    </div>
<% end %>

app/views/appointments/edit.html.erb
<h1>Edit <%= @appointment.title %></h1>
<%= render "form" %>

app/views/appointments/new.html.erb
<h1>Add an Appointment</h1>
<%= render "form" %>

app/views/appointments/show.html.erb
<h3><%= @appointment.title %></h3>
<p>Doctor: <%= @appointment.doctor %></p>
<p>Date: <%= @appointment.datetime.strftime('%a, %B %e, %G') %></p>
<p>Time: <%= @appointment.datetime.strftime('%l:%M%P') %></p>
<p>Address: <%= @appointment.address %></p>
<p>Assigned User: <%= @appointment.assigned_user ? @appointment.assigned_user.email : "Awaiting assignment" %></p>
<p>Suggested User: <%= @appointment.suggested_user ? @appointment.suggested_user.email : '' %></p>

<%= link_to "Edit Appointment", edit_patient_team_appointment_path, class: "btn btn-success" %>
<%= link_to "Delete Appointment", [@patient, :team, @appointment], method: :delete, class: 'btn btn-danger', data: {confirm: "Are you sure you want to delete #{@appointment.title}?" } %>
<p><%= link_to "Back to Team Calendar", patient_team_path %></p>